GARCIA-1 name changes
catbox-dev/lifx-python pull request #1
Opened 2023-06-26 21:04 UTC by cgarcia-iwa

Description:

Writer name was added

2023-06-26 21:07 UTC, catbox-dev requested changes
Request changes

2023-06-26 21:08 UTC, catbox-dev approved these changes

2023-06-27 19:56 UTC, catbox-dev requested changes
comentarios ejemplo

2023-06-27 19:56 UTC, catbox-dev commented on Names.txt
> +-- CAGD
comentario 1

2023-06-27 19:56 UTC, catbox-dev commented on Names.txt
> +GARCIA DOMINGUEZ CARLOS E
comentario 2

2023-06-27 19:56 UTC, Ulux05 commented on Names.txt
> --- CAGD
comentario 2

2023-06-27 19:56 UTC, catbox-dev approved these changes

2023-06-27 19:57 UTC, merged